REMAINING

diff --git a/misc/stm32f429zitx-build b/misc/stm32f429zitx-build
--- a/misc/stm32f429zitx-build
+++ b/misc/stm32f429zitx-build
@@ -2,41 +2,25 @@
 
 # TODO(Ryan): Investigate useful pre-commit hooks, e.g. ensure file naming convention
 
-# versions don't differentiate binary types
-# GNU build id in .notes section
-# -Wl,--build-id; readelf -n
-# .gnu_build_id: (required as objcopy only LOAD)
-# {
-#   PROVIDE(g_note_build_id = .); (provide symbol)
-#   *(.note.gnu.build-id)
-# } > rom
 
-
-# IMPORTANT(Ryan): We cannot exit on error otherwise when tests fail, build will exit prematurely
-# set -oue pipefail
-set -u
 
 build_start_time=$(date +%s.%N)
 
-if [[ "$1" != "app" && "$1" != "tests" ]]; then
+if [[ "$1" == "app" ]]; then
+  set -oue pipefail
+elif [[ "$1" == "tests" ]]; then
+  # IMPORTANT(Ryan): We cannot exit on error otherwise when tests fail, build will exit prematurely
+  set -u
+else
   printf "Usage: ./build <app|tests>\n" >&2
   exit 1
 fi
 
 BUILD_TYPE="$1"
 
-error() {
-  printf "Error: %s\n" "$1" >&2
-  exit 1
-}
-
-push_dir() {
-  command pushd "$@" > /dev/null
-}
-
-pop_dir() {
-  command popd "$@" > /dev/null
-}
+error() { printf "Error: %s\n" "$1" >&2 && exit 1; }
+push_dir() { command pushd "$@" > /dev/null; }
+pop_dir() { command popd "$@" > /dev/null; }
 
 # TODO(Ryan): ccache for when switching between branches affecting mtime
 
@@ -192,6 +176,14 @@ if [[ "$param_arch" == "arm" && "$param_compiler" == "arm-none-eabi-gcc" && "$pa
   #  CONSOLE
   #  SIGNED BUILDS: It might make the most sense to have a separate “development” key for signing/encrypting development builds. A key that is separate and has different security concerns than the production key. 
   # 
+
+  LINKER_FLAGS+=( "-Wl,--build-id" )
+  # IMPORTANT(Ryan): For embedded linker script (as objcopy only LOAD):
+  # .gnu_build_id: 
+  # {
+  #   PROVIDE(g_note_build_id = .); (provide symbol)
+  #   *(.note.gnu.build-id)
+  # } > rom
 
   if [[ "$param_mode" == "debug" ]]; then
     common_debug_flags=( "-Wno-unused-function" "-Wno-unused-variable"  "-Wno-unused-but-set-variable" "-Wno-unused-parameter" "-Wno-unused-result" )
